server:
  port: 10098
  servlet:
    context-path: /api/service/

spring:
  application:
    name: dataware-scheduler
  security:
    user:
      name: hitocas
      password: Hitocas123
  rabbitmq:
    host: 192.168.10.240
    port: 5672
    username: Admin
    password: Hitocas123
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.240:33306/dataware?allowMultiQueries=true
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 60000
      pool-name: DatebookHikariCP
      connection-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  data:
    elasticsearch:
      cluster-nodes: 192.168.10.240:9300
      cluster-name: zkht
      repositories: true
  elasticsearch:
    rest:
      uris: 192.168.10.240:9200
      
mybatis:
  mapper-locations: classpath:mapper/*.xml
  mybatis:
    config-location: classpath:config/mybatis-config.xml        

elasticsearch:
  ip: 192.168.10.240
  port: 9200
  cluster-name: zkht

eureka:
  client:
    serviceUrl:
      defaultZone: http://hitocas:Hitocas123@localhost:10090/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#船的默认补全查询的条数
ship:
  completion:
    size: 10
